lib/shop_scraper_web/router.ex
defmodule ShopScraperWeb.Router do
  require Mandarin.Router

  use ShopScraperWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin_layout do
    plug(:put_layout, {ShopScraperWeb.AdminLayoutView, "layout.html"})
  end

  scope "/", ShopScraperWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", ShopScraperWeb do
  #   pipe_through :api
  # end

  scope "/admin", ShopScraperWeb.Admin, as: :admin do
    pipe_through([:browser, :admin_layout])

    Mandarin.Router.resources "/shops", ShopController
    post "/shops/:id/test", ShopController, :test
    get "/shops/:id/results", ShopController, :results
    post "/shops/:id/apply", ShopController, :apply

    Mandarin.Router.resources "/attributes", AttributeController
    post "/attributes/fetch_from_woocommerce", AttributeController, :fetch_from_woocommerce
    Mandarin.Router.resources "/products", ProductController
    Mandarin.Router.resources "/jobs", JobController
    Mandarin.Router.resources "/prices", PriceController
  end
end

lib/shop_scraper/woocommerce/product.ex
defmodule ShopScraper.Woocommerce.Product do
  import ShopScraper.Woocommerce

  alias ShopScraper.Admin
  alias ShopScraper.Admin.Product
  alias ShopScraper.Woocommerce.Attribute
  alias ShopScraper.Woocommerce.ProductVariation
  alias ShopScraper.Repo

  def fetch_all_products() do
    list_products()
    |> Enum.map(fn (product) ->
      name_params =
        %{name: product["name"],
          woocommerce_id: product["id"]
          # prices: prices,
          # attribute_values: attr_values
        }
      with {:ok, saved_product} <- ShopScraper.Admin.create_product(name_params) do
        attr_values =
          product["attributes"]
          |> Enum.filter(&(&1["variation"] == false))
          |> Enum.map(fn (attr) ->
            %{attribute: Admin.get_attribute_by_woocommerce_id(attr["id"]),
              value: List.first(attr["options"]),
              product: saved_product
            } |> ShopScraper.Admin.create_attribute_value()
          end)
        prices =
          ProductVariation.list_product_variations(product["id"])
          |> Enum.map(fn (variation) ->
            url = case Regex.run(~r/<p>(http.*)<\/p>/, variation["description"], capture: :all_but_first) do
              nil -> variation["description"]
              [match] -> match
            end
            %{amount: variation["price"],
              quantity: Enum.find(variation["attributes"], &(&1["name"] == "Number of Seeds"))["option"],
              shop: Enum.find(variation["attributes"], &(&1["name"] == "Store"))["option"] |> Attribute.normalize_shop_name() |> Admin.get_shop_by_name(),
              url: url,
              woocommerce_id: variation["id"],
              product: saved_product
            } |> ShopScraper.Admin.create_price()
          end)
       %{saved_product | attribute_values: attr_values, prices: prices}
      end
    end)
  end

  def create_or_update_product(%Product{woocommerce_id: nil} = product) do
    create_product(product)
  end
  def create_or_update_product(%Product{} = product) do
    update_product(product)
  end

  def create_products() do
    ShopScraper.Admin.list_products([])
    |> Enum.each(fn (product) -> create_or_update_product(product) end)
  end

  def update_products_name() do
    ShopScraper.Admin.list_products([])
    # |> Enum.take(1)
    |> Enum.each(fn (product) -> update_product(product) end)
  end

  def get_product(product) do
    get_one_product(product.woocommerce_id)
    |> Jason.decode!
    |> IO.inspect()
  end

  def attributes_list do
    [
      %{"id" => 25, "visible" => true},  # Product Name
      %{"id" => 24, "visible" => true},  # Breader / bank
      %{"id" => 12, "visible" => false}, # Cheapest Store,
      %{"id" => 11, "visible" => false}, # Cheapest (1) Seed 
      %{"id" => 7,  "visible" => true},  # Phenotype (Sativa/Indica)
      %{"id" => 18, "visible" => true},  # Seed Type
      %{"id" => 10,                      # Store
        "options" => ["Sensi Seeds", "I Love Growing Marijuana"],
        "visible" => false,
        "variation" => true
      },
      %{"id" => 19, "visible" => true},  # Lineage
      %{"id" => 14, "visible" => true},  # Flowering Length (Days)
      %{"id" => 13, "visible" => false}, # Flowering Length
      %{"id" => 22, "visible" => true},  # Plant Characteristics
      %{"id" => 21, "visible" => true},  # Climat Resistance
      %{"id" => 15, "visible" => true},  # Outdoor Climat
      %{"id" => 16, "visible" => true},  # Product Awards
      %{"id" => 23, "visible" => true},  # Grower Difficulty
      %{"id" => 5,  "visible" => true},  # High/Effects
      %{"id" => 20, "visible" => true},  # Medical Usage
      %{"id" => 26, "visible" => true},  # Possible Side Effects
      %{"id" => 2,  "visible" => true},  # Taste/Flavor
      %{"id" => 6,  "visible" => true},  # Odor
      %{"id" => 3,  "visible" => true},  # THC Levels
      %{"id" => 4,  "visible" => true},  # CBD Levels
      %{"id" => 27, "visible" => true},  # THC vs CBD
      %{"id" => 17, "visible" => true},  # Yield
      %{"id" => 9,                       # Number of seeds
        "options" => ["1", "3", "5", "10", "20", "25"],
        "visible" => false,
        "variation" => true
      }
    ]
    |> Enum.with_index()
    |> Enum.map(fn {el, i} -> Map.put(el, "position", i) end)
  end

  def product_params(%Product{} = product, options \\ %{}) do
    %{
      "name" => product.name,
      # "regular_price" => ShopScraper.Admin.minimum_price(product),
      "type" => "variable"
    }
    |> Map.merge(options)
  end

  def create_product(%Product{} = product) do
    options = %{"status" => "draft",
                "attributes" => attributes_list()}
    product_map = product_params(product, options)
    %{"id" => woocommerce_id} =
      post_create_product(product_map)
      |> Jason.decode!()
    ShopScraper.Admin.update_product(product, %{"woocommerce_id" => woocommerce_id})
  end

  def update_product(%Product{} = product) do
    product_map = product_params(product)
    %{"id" => _woocommerce_id} =
      post_update_product(product_map, product.woocommerce_id)
      |> Jason.decode!()
  end

  def list_products() do
    get_depaginated("/wp-json/wc/v2/products")
  end

  def get_one_product(product_id) do
    get("/wp-json/wc/v2/products/#{product_id}")
  end

  defp post_create_product(params) do
    post("/wp-json/wc/v2/products", params)
  end

  def post_update_product(params, product_id) do
    post("/wp-json/wc/v2/products/#{product_id}", params)
  end
end

lib/shop_scraper_web/views/admin_layout_view.ex
defmodule ShopScraperWeb.AdminLayoutView do
  use ShopScraperWeb, :view
  # Add Forage routes!
end

defimpl Phoenix.HTML.Safe, for: Map do
  def to_iodata(data) do
    data |> Jason.encode!() |> Jason.Formatter.pretty_print_to_iodata()
  end
end

lib/shop_scraper_web/templates/admin_layout/layout.html.eex
<!DOCTYPE html>
<%#
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
%>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Mandarin | Starter</title>
  <%# Tell the browser to be responsive to screen width %>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/bootstrap.min.css") %>">
  <%# Font Awesome %>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/font-awesome.min.css") %>">
  <%# Ionicons %>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/ionicons.min.css") %>">
  <%# Theme style %>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/AdminLTE.min.css") %>">
  <%# AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. %>
        <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/skins/_all-skins.min.css") %>">

  <%# Google Font %>
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<%#
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
%>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
  <header class="main-header">
    <%= render ShopScraperWeb.AdminLayoutView, "main-header.html", assigns %>
  </header>

  <%# Left sidebar %>
  <aside class="main-sidebar">
    <section class="sidebar">
      <%= render ShopScraperWeb.AdminLayoutView, "sidebar.html", assigns %>
    </section>
  </aside>

  <%# Page content %>
  <div class="content-wrapper">
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <%= render @view_module, @view_template, assigns %>
  </div>

  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      Anything you want
    </div>
    <strong>Copyright &copy; 2019 <a href="#">Company</a>.</strong> All rights reserved.
  </footer>

  <div class="control-sidebar-bg">
  </div>
</div>

<%# REQUIRED JS SCRIPTS %>
<%# Phoenix's Javascript so that "delete links" work as they should %>
<script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
<%# jQuery 3 %>
<script src="<%= Routes.static_path(@conn, "/js/jquery.min.js") %>"></script>
<%# Bootstrap 3.3.7 %>
<script src="<%= Routes.static_path(@conn, "/js/bootstrap.min.js") %>"></script>
<%# AdminLTE App %>
<script src="<%= Routes.static_path(@conn, "/js/adminlte.min.js") %>"></script>

<link href="<%= Routes.static_path(@conn, "/css/select2.min.css") %>"> rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script>
// In your Javascript (external .js resource or <script> tag)
$(document).ready(function() {
  $('[data-forage-select2-widget="true"]').each(
    function(index, node) {
      // Extract configuration options from the HTML element
      var baseUrl = node.dataset.url;
      var field = node.dataset.field;
      // Next, we create some extra storage to help us convert offset-based pagination
      // into cursor-based pagination.
      //
      // With offset-based pagination, the pages are numbered (i.e. 1, 2, 3...).
      // On the other hand, with cursor-based pagination, we have only an abstract token,
      // which serves as a link to the next page.
      //
      // To convert page numbers to tokens, we simply define a map that stores the token
      // for every page number.
      // That way, Select2 can continue to ask for page number 1, 2, 3, etc. because we
      // know how to convert the page number into out tokens
      var lastTerm = "";
      var pageToAfterToken = {1: null};
      // Turn the node into a select2 box
      $(node).select2({
        // Use AJAX to get JSON data from the server
        ajax: {
        url: baseUrl,
        data: function (params) {
          var page = params.page || 1;
          var term = params.term || "";
          // Build the query
          var query = {};
          query["_search[" + field + "][op]"] = "contains";
          query["_search[" + field + "][val]"] = term;
          // If we don't have a token or if the query string has changed,
          // we don't want to reuse the pagination token.
          var afterToken = pageToAfterToken[page];
          if(afterToken && lastTerm == term) {
            query["_pagination[after]"] = afterToken;
          }

          // Query parameters will be ?search=[term]&type=public
          return query;
        },
        processResults: function (data, params) {
          var page = params.page || 1
          lastTerm = params.term || "";
          // With the request for the current page we also receive
          // the token for the next page
          pageToAfterToken[page + 1] = data.pagination.after;
          return data;
        },
        dataType: 'json',
        placeholder: "..."
      }
    });
  })
});
</script>

<%# Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. %>
</body>
</html>

lib/shop_scraper_web/templates/admin_layout/main-header.html.eex
<a href="#" class="logo">
  
  <span class="logo-mini"><b>B</b>CT</span>
  
  <span class="logo-lg"><b>BUREAU</b>CRAT</span>
</a>


<nav class="navbar navbar-static-top" role="navigation">
  
  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">Toggle navigation</span>
  </a>
  
  <div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
      
      <li>
        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
      </li>
    </ul>
  </div>
</nav>

lib/shop_scraper_web/templates/admin_layout/sidebar.html.eex
<ul class="sidebar-menu" data-widget="tree">
  <%# Common link labels to reduce boilerplate %>
  <% index_label = raw(~s'<i class="fa fa-search"></i> Index') %>
  <% new_label = raw(~s'<i class="fa fa-plus"></i> New') %>
  <% edit_label = raw(~s'<i class="fa fa-edit"></i> Edit') %>
  <% delete_label = raw(~s'<i class="fa fa-trash"></i> Delete') %>
  <%#
    The space between the comments below will be populated with
    links generated by the Mandarin generators.
    - If you wish to have such links populated automatically,
      don't delete the comments.
    - If you don't wish the links to be populated automatically,
      then delete the comments
  %>
  <li class="header">Resources</li>
  <%# %% Resource Links - START %% %>

  <%# Sidebar links for Shop %>
  <li class="treeview<%= if @mandarin_resource == :shop do %> active menu-open<% end %>">
    <a href="#">
      <i class="fa fa-th"></i> <span>Shop</span>
    </a>
    <ul class="treeview-menu">
      <li><%= link(index_label, to: Routes.admin_shop_path(@conn, :index)) %></li>
      <li><%= link(new_label, to: Routes.admin_shop_path(@conn, :new)) %></li>
      <%= if Map.get(assigns, :shop) && @shop.id do %>
        <li><%= link(edit_label, to: Routes.admin_shop_path(@conn, :edit, @shop.id)) %></li>
        <li><%= link(delete_label, to: Routes.admin_shop_path(@conn, :delete, @shop.id), method: :delete, data: [confirm: "Are you sure?"]) %></li>
      <% end %>
    </ul>
  </li>

  <%# Sidebar links for Product %>
  <li class="treeview<%= if @mandarin_resource == :product do %> active menu-open<% end %>">
    <a href="#">
      <i class="fa fa-th"></i> <span>Product</span>
    </a>
    <ul class="treeview-menu">
      <li><%= link(index_label, to: Routes.admin_product_path(@conn, :index)) %></li>
      <li><%= link(new_label, to: Routes.admin_product_path(@conn, :new)) %></li>
      <%= if Map.get(assigns, :product) && @product.id do %>
        <li><%= link(edit_label, to: Routes.admin_product_path(@conn, :edit, @product.id)) %></li>
        <li><%= link(delete_label, to: Routes.admin_product_path(@conn, :delete, @product.id), method: :delete, data: [confirm: "Are you sure?"]) %></li>
      <% end %>
    </ul>
  </li>

  <%# Sidebar links for Attribute %>
  <li class="treeview<%= if @mandarin_resource == :attribute do %> active menu-open<% end %>">
    <a href="#">
      <i class="fa fa-th"></i> <span>Attribute</span>
    </a>
    <ul class="treeview-menu">
      <li><%= link(index_label, to: Routes.admin_attribute_path(@conn, :index)) %></li>
      <li><%= link(new_label, to: Routes.admin_attribute_path(@conn, :new)) %></li>
      <%= if Map.get(assigns, :attribute) && @attribute.id do %>
        <li><%= link(edit_label, to: Routes.admin_attribute_path(@conn, :edit, @attribute.id)) %></li>
        <li><%= link(delete_label, to: Routes.admin_attribute_path(@conn, :delete, @attribute.id), method: :delete, data: [confirm: "Are you sure?"]) %></li>
      <% end %>
    </ul>
  </li>
  <%# %% Resource Links - END %% %>
</ul>